# Generated by Django 3.2 on 2023-04-14 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('photo', models.ImageField(null=True, upload_to='files')),
                ('name', models.CharField(max_length=32)),
                ('closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(null=True)),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default=None, max_length=6, null=True)),
                ('type', models.CharField(choices=[('USER_TICKET', 'USER_TICKET'), ('PUBLIC_GROUPE', 'PUBLIC_GROUPE'), ('PRIVATE_GROUPE', 'PRIVATE_GROUPE'), ('PRIVATE_CHAT', 'PRIVATE_CHAT')], default='USER_TICKET', max_length=14)),
                ('read_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'chat_rooms',
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('is_creator', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('action_permission', models.IntegerField(default=221)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_member', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_members',
            },
        ),
        migrations.AddConstraint(
            model_name='chatmember',
            constraint=models.UniqueConstraint(fields=('chat_room', 'user'), name='unique_user_room'),
        ),
    ]
