# Generated by Django 4.2 on 2023-04-28 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', auto_created=True, min_length=7, prefix='', primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('is_creator', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('action_permission', models.IntegerField(default=15)),
            ],
            options={
                'db_table': 'chat_members',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', auto_created=True, min_length=7, prefix='', primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('file', models.FileField(upload_to='file')),
                ('file_pic', models.ImageField(null=True, upload_to='file_picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_upload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_uploads',
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', hashid_field.field.BigHashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', auto_created=True, min_length=13, prefix='', primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mentions',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', auto_created=True, min_length=7, prefix='', primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('type', models.CharField(choices=[('TEXT', 'TEXT'), ('FILE', 'FILE'), ('ONLINE', 'ONLINE'), ('NOTICE', 'NOTICE'), ('TYPING', 'TYPING'), ('SENDING', 'SENDING')], max_length=7)),
                ('text', models.TextField(null=True)),
                ('seen', models.BooleanField(default=False)),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_file', to='chat.fileupload')),
                ('mentions', models.ManyToManyField(related_name='user_mentions', through='chat.Mention', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_to_message', to='chat.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to='chat.chatmember')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
        migrations.CreateModel(
            name='PredefinedMessage',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', auto_created=True, min_length=7, prefix='', primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('text', models.TextField(null=True)),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_predefinedmessage', to='chat.fileupload')),
            ],
            options={
                'db_table': 'predefined_messages',
            },
        ),
        migrations.CreateModel(
            name='UnSeen',
            fields=[
                ('id', hashid_field.field.BigHashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', auto_created=True, min_length=13, prefix='', primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unseen',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', auto_created=True, min_length=7, prefix='', primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_message', to='chat.predefinedmessage')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='unseen_users',
            field=models.ManyToManyField(related_name='user_unseen', through='chat.UnSeen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mention',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
        migrations.AddField(
            model_name='mention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', auto_created=True, min_length=7, prefix='', primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('photo', models.ImageField(null=True, upload_to='group_picture')),
                ('name', models.CharField(max_length=32)),
                ('closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(null=True)),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default=None, max_length=6, null=True)),
                ('type', models.CharField(choices=[('USER_TICKET', 'USER_TICKET'), ('PUBLIC_GROUPE', 'PUBLIC_GROUPE'), ('PRIVATE_GROUPE', 'PRIVATE_GROUPE'), ('PRIVATE_CHAT', 'PRIVATE_CHAT')], default='USER_TICKET', max_length=14)),
                ('read_only', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(through='chat.ChatMember', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_rooms',
            },
        ),
        migrations.AddField(
            model_name='chatmember',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_member', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'group'), name='unique_reporter_group'),
        ),
        migrations.AddConstraint(
            model_name='chatmember',
            constraint=models.UniqueConstraint(fields=('chat_room', 'user'), name='unique_user_room'),
        ),
    ]
