# Generated by Django 3.2 on 2023-02-24 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(null=True)),
                ('importance', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', max_length=10)),
                ('type', models.CharField(choices=[('TICKET', 'TICKET'), ('GROUPE', 'GROUPE'), ('PRIVATE', 'PRIVATE')], default='TICKET', max_length=10)),
            ],
            options={
                'db_table': 'chat_rooms',
            },
        ),
        migrations.CreateModel(
            name='ChatUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('file', models.FileField(upload_to='chat_files')),
                ('file_pic', models.FileField(null=True, upload_to='chat_files')),
                ('file_type', models.CharField(choices=[('VOICE', 'VOICE'), ('FILE', 'FILE'), ('VIDEO', 'VIDEO'), ('IMAGE', 'IMAGE')], max_length=10)),
            ],
            options={
                'db_table': 'chat_uploads',
            },
        ),
        migrations.CreateModel(
            name='PredefindMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('text', models.TextField(null=True)),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_predefinedmessage', to='chat.chatupload')),
            ],
            options={
                'db_table': 'predefind_messages',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefinedmessage_report', to='chat.predefindmessage')),
                ('reportee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportee_report', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('text', models.TextField(null=True)),
                ('seen', models.BooleanField(default=False)),
                ('seen_at', models.DateTimeField(null=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_message', to='chat.chatroom')),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_message', to='chat.chatupload')),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_to_message', to='chat.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, serialize=False)),
                ('is_creator', models.BooleanField(default=False)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_member', to='chat.chatroom')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_members',
            },
        ),
        migrations.AddConstraint(
            model_name='chatroommember',
            constraint=models.UniqueConstraint(fields=('chat_room', 'profile'), name='unique_profile_room'),
        ),
    ]
